## Primera Clase: Repaso

### 1. Tipos de Variables

En Python existen muchos tipos de variables. Entre las más usadas están las numéricas (Enteros int, decimales "cortos" double, decimales de punto flotante float,números complejos, etc), las cadenas de caracteres (strings), las listas, los arrays (vectores o matrices) y los diccionarios (aunque estos últimos no tanto). A continuación se explicarán un poco más a detalle. 

### 1.1 Variables numéricas

Como se dijo antes, entre las variables numéricas que tiene Python se encuentran los enteros, decimales cortos y decimales de punto flotante. Generalmente en Python los double no son muy usados. Sin embargo los demás tipos de variables si. Para declarar estas variables no hay necesidad de determinar su tipo (como en C o C++), ya que Python automáticamente detecta el tipo de variable usado. Basta solamente con definir las variables, como se muestra a continuación:

In [52]:
a = 5 # se declara un entero 
b = 10.1 # se declara un decimal de punto flotante float
c = 1.5 + 2.3j # se declara un número complejo
print(type(a), type(b), type(c)) # Se imprime el tipo de variable de a, b y c.

<class 'int'> <class 'float'> <class 'complex'>


Como se observa, las variables a,b y c son un entero (int), un decimal de punto flotante (float) y un número complejo (complex).

### Operaciones

Las operaciones más conocidas entre variables numéricas son las usuales (suma, resta, multiplicación y división). Sin embargo hay algunas otras que Python nos puede proporcionar. Algunas operaciones son transformaciones entre las distintas variables numéricas, es decir, pasar de int a float, de float a complex, de complex a int, de float a int, etc. Otras pueden ser el módulo entre dos números, el valor absoluto, el complejo conjugado, entre otras. A continuación se muestran algunas operaciones explícitas. 

In [53]:
a,b,c,d,e,f,g,h,i = 2, 5, 9, 10.1, 23.46555885, 98.3, 1.6+0.8j, 8.4+8.8j, 9.6+4.5j # se declaran variables al tiempo (3 int, 3 float y 3 complex)

print("El negativo de e")
print(-e) # El negativo de e
print("\n")

print("a más b")
print(a+b) # a más b
print("\n")

print("a menos b")
print(a-b) # a menos b
print("\n")

print("a multiplicado por c")
print(a*c) # a multiplicado por c
print("\n")

print("a dividido en b ")
print(a/b) # a dividido en b 
print("\n")

print("Convierto el int 'a' en un float")
print(float(a)) # Convierto el int "a" en un float
print("\n")

print("Convierto el float 'd' en entero")
print(int(d)) # Convierto el float "d" en entero
print("\n")

print("Convierto el int 'a' en un complex con parte imaginaria cero")
print(complex(a,0)) # Convierto el int "a" en un complex con parte imaginaria cero
print("\n")

print("Convierto el float 'd' en un complejo con parte real cero")
print(complex(0,d)) # Convierto el float "d" en un complejo con parte real cero
print("\n")

print("Complejo conjugado de h")
print(h.conjugate()) # Complejo conjugado de h
print("\n")

print("c modulo a (Residuo de la division entre c y a)")
print(c % a) # c modulo a (Residuo de la division entre c y a)
print("\n")

print("c elevado a la potencia a")
print(pow(c,a)) # c elevado a la potencia a
print("\n")

print("c elevado a la potencia a...de nuevo")
print(c**a) # c elevado a la potencia a...de nuevo
print("\n")

print("Redondear la variable 'e' a solo dos decimales")
print(round(e,2)) # Redondear la variable "e" a solo dos decimales
print("\n")

El negativo de e
-23.46555885


a más b
7


a menos b
-3


a multiplicado por c
18


a dividido en b 
0.4


Convierto el int 'a' en un float
2.0


Convierto el float 'd' en entero
10


Convierto el int 'a' en un complex con parte imaginaria cero
(2+0j)


Convierto el float 'd' en un complejo con parte real cero
10.1j


Complejo conjugado de h
(8.4-8.8j)


c modulo a (Residuo de la division entre c y a)
1


c elevado a la potencia a
81


c elevado a la potencia a...de nuevo
81


Redondear la variable 'e' a solo dos decimales
23.47




Hay más operaciones entre variables numericas que pueden ser encontradas en http://www.python-ds.com/python-3-numeric-operations

### 1.2 Cadenas de caracteres

Otro tipo de variable interesante de explorar son las cadenas de caracteres, que vendrían siendo conjuntos de letras, numeros y algunos simbolos para formar palabras. Generalmente se usan para dar nombres a archivos, importarlos desde el computador, dar el titulo de una gráfica o de sus ejes, entre otras cosas. Para crear uno solo basta con declararlo de la siguiente manera:

In [3]:
s = "Hola Mundo 123" # Se crea el string
print(s) # Se imprime la cadena de caracteres 
print(type(s)) # Se imprime el tipo de variable de "s". Fijarse que es str.

Hola Mundo 123
<class 'str'>


### Operaciones

Con strings se pueden realizar diversas operaciones, como las siguientes:

In [4]:
s1 = "Hola"
s2 = "Hola "
s3 = "Mundo"
s4 = "123"
s5 = "Hola Mundo"
a = 123.45

print("Suma de strings s1 y s3. Se pegan ambos strings ")
print(s1 + s3) # Suma de strings s1 y s3. Se pegan ambos strings 
print("\n")

print("Suma de strings s2 y s3. Se pegan ambos strings. Notar que el espacio se considera como otra 'letra' extra y queda en el resultado ")
print(s2 + s3) # Suma de strings s2 y s3. Se pegan ambos strings. Notar que el espacio se considera como otra "letra" extra y queda en el resultado 
print("\n")

print("Convertir un número en string. Se imprime str(a) junto con el tipo de dato que es str(a) para observar que efectivamente str(a) es un string")
print(str(a), type(str(a))) # Convertir un número en string. Se imprime str(a) junto con el tipo de dato que es str(a) para observar que efectivamente str(a) es un string
print("\n")

print("Se suma s1 junto con a (convertido en string). Si se suma s1 directamente con 'a' saldrá un error porque no se pueden sumar strings con numeros directamente")
print(s1 + str(a)) # Se suma s1 junto con a (convertido en string). Si se suma s1 directamente con "a" saldrá un error porque no se pueden sumar strings con numeros directamente
print("\n")

print("Se imprime el string s1 desde su primera letra hasta la segunda")
print(s1[:2]) # Se imprime el string s1 desde su primera letra hasta la segunda
print("\n")

print("Se imprime el string s1 desde su tercera letra hasta la última")
print(s1[2:]) # Se imprime el string s1 desde su tercera letra hasta la última
print("\n")

print("Se imprime el string s3 desde su segunda letra hasta la cuarta. En general s3[i:j] retorna el string s3 desde la letra (o simbolo) i hasta el j-1. Recordar que los índices en Python van desde el cero, así que el indice 1 es la segunda letra y el índice 3 = 4-1 es la cuarta letra.")
print(s3[1:4]) # Se imprime el string s3 desde su segunda letra hasta la cuarta. En general s3[i:j] retorna el string s3 desde la letra (o simbolo) i hasta el j-1. Recordar que los índices en Python van desde el cero, así que el indice 1 es la segunda letra y el índice 3 = 4-1 es la cuarta letra.
print("\n")

print("Cuenta el numero de 'n' que hay en el string")
print(s3.count("n")) # Cuenta el numero de "n" que hay en el string
print("\n")

print("Pone todo el string en mayusculas")
print(s3.upper()) # Pone todo el string en mayusculas
print("\n")

print("Pone todo el string en minusculas")
print(s3.lower()) # Pone todo el string en minusculas
print("\n")

print("Retorna True o False dependiendo de si el string s3 empieza con el string 'Mun' ")
print(s3.startswith("Mun")) # Retorna True o False dependiendo de si el string s3 empieza con el string "Mun"
print("\n")

print("Retorna True o False dependiendo de si el string s3 termina con el string 'do' ")
print(s3.endswith("do")) # Retorna True o False dependiendo de si el string s3 termina con el string "do"
print("\n")

print("El string s5, que se compone de dos 'palabras' separadas por un espacio, se separa en una lista en donde cada componente de la lista es una de las palabras")
print(s5.split()) # El string s5, que se compone de dos "palabras" separadas por un espacio, se separa en una lista en donde cada componente de la lista es una de las palabras
print("\n")

print("Retorna el numero de caracteres que tiene el string s5 (el espacio se cuenta como caracter)")
print(len(s5)) # Retorna el numero de caracteres que tiene el string s5 (el espacio se cuenta como caracter)
print("\n")

print("Usar un índice negativo implica contar los caracteres de la lista de derecha a izquierda y no de izquierda a derecha como es de costumbre. De forma de s5[-1] es el último caracter del string, s5[-2] es el penúltimo, s5[-3] es el antepenúltimo y así sucesivamente")
print(s5[-1]) # Usar un índice negativo implica contar los caracteres de la lista de derecha a izquierda y no de izquierda a derecha como es de costumbre. De forma de s5[-1] es el último caracter del string, s5[-2] es el penúltimo, s5[-3] es el antepenúltimo y así sucesivamente.
print("\n")


print(s5[-3:-1]) 

Suma de strings s1 y s3. Se pegan ambos strings 
HolaMundo


Suma de strings s2 y s3. Se pegan ambos strings. Notar que el espacio se considera como otra 'letra' extra y queda en el resultado 
Hola Mundo


Convertir un número en string. Se imprime str(a) junto con el tipo de dato que es str(a) para observar que efectivamente str(a) es un string
123.45 <class 'str'>


Se suma s1 junto con a (convertido en string). Si se suma s1 directamente con 'a' saldrá un error porque no se pueden sumar strings con numeros directamente
Hola123.45


Se imprime el string s1 desde su primera letra hasta la segunda
Ho


Se imprime el string s1 desde su tercera letra hasta la última
la


Se imprime el string s3 desde su segunda letra hasta la cuarta. En general s3[i:j] retorna el string s3 desde la letra (o simbolo) i hasta el j-1. Recordar que los índices en Python van desde el cero, así que el indice 1 es la segunda letra y el índice 3 = 4-1 es la cuarta letra.
und


Cuenta el numero de 'n' que hay en e

Hay muchas más operaciones interesantes con strings, pero estas son algunas de las más usadas. Para ver más ir a https://www.learnpython.org/en/Basic_String_Operations

### 1.3 Listas

Una lista no es más que un conjunto de datos de todo tipo organizados bajo una misma estructura, encerrados por un par de corchetes cuadrados. Para declarar una lista basta con hacer lo siguiente:

In [5]:
l1 = [] # Lista vacia
l2 = [1,2,3,4,5,6,7,8,9] # Lista de numeros enteros
l3 = [1.2, 2.3, 3.4, 4.5, 5.6, 6.7] # Lista de numeros de punto flotante
l4 = ["Hola", "Mundo", "123"] # Lista de strings
l5 = ["Hola", 1.234, 25] # Lista de varios tipos de elementos

print(l1)
print(l2)
print(l3)
print(l4)
print(l5)

[]
[1, 2, 3, 4, 5, 6, 7, 8, 9]
[1.2, 2.3, 3.4, 4.5, 5.6, 6.7]
['Hola', 'Mundo', '123']
['Hola', 1.234, 25]


### Operaciones

Entre las operaciones sobre listas se encuentran los siguientes:

In [6]:
l1 = [] # Lista vacia
l2 = [1,2,3,4,5,6,7,8,9] # Lista de numeros enteros
l3 = [1.2, 2.3, 3.4, 4.5, 5.6, 6.7] # Lista de numeros de punto flotante
l4 = ["Hola", "Mundo", "123"] # Lista de strings
l5 = ["Hola", 1.234, 25] # Lista de varios tipos de elementos

print(l4 + l5) # Suma de l4 y l5. Las listas se pegan la una a la otra, como en los strings. La resta no existe entre listas
print(l2[1:4]) # Se obtiene una nueva lista, con los elementos desde el i=1 (segundo elemento) hasta el i=3 (cuarto elemento). En general l2[i:j] retorna la lista l2 desde el elemento i hasta el j-1.

l5[0] = "Gatito" # Se reemplaza el primero elemento (i=0) de la lista por la palabra "Gatito" y se imprime el resultado. No solo vale reemplazar por strings sino por cualquier tipo de datos
print(l5)

print(len(l5)) # Retorna la cantidad de elementos en la lista

l5.append(12345) # Se añade en la última posicion de la lista el número 12345. Se vale no solo añadir enteros sino toda clase de datos
print(l5)

l5.insert(2,"Perrito") # Se añade en la posición i=2 (tercera posicion) de la lista el string "Perrito". Vale para cualquier tipo de dato
print(l5)

l5.pop() # Elimina el último elemento de la lista
print(l5)

l5.pop(1) # Elimina el elemento i=1 (segundo elemento de la lista)
print(l5)

['Hola', 'Mundo', '123', 'Hola', 1.234, 25]
[2, 3, 4]
['Gatito', 1.234, 25]
3
['Gatito', 1.234, 25, 12345]
['Gatito', 1.234, 'Perrito', 25, 12345]
['Gatito', 1.234, 'Perrito', 25]
['Gatito', 'Perrito', 25]


Hay muchas más operaciones entre listas, pero estas son las principales. Para ver más ir a https://www.w3schools.com/python/python_lists.asp 

### 1.4 Arrays 

Los arrays hacen básicamente lo mismo que hacen las listas. La gran diferencia radica en el hecho de que los arrays pueden ser operados como si fueran vectores o matrices. Para crear un array es muy similar a crear una lista. Sin embargo como primer requisito es indispensable tener cargada la librería Numpy.

In [7]:
import numpy as np # Cargar la librería Numpy bajo el pseudonimo "np"

array_1 = np.array([1,2,3,4,5,6,7,8,9]) # Se crea un vector de numeros enteros del 1 al 9
array_2 = np.array(["Gatito", 1, "Perrito", 2])
array_3 = np.array([[1,2,3],[4,5,6],[7,8,9]]) # Se crea la matriz con entradas 1 2 3
                                              #                                4 5 6
                                              #                                7 8 9
                                              # La matriz la creamos como un vector que contiene los vectores fila de la matriz
                                            
print(array_1)
print(array_2)
print(array_3)

[1 2 3 4 5 6 7 8 9]
['Gatito' '1' 'Perrito' '2']
[[1 2 3]
 [4 5 6]
 [7 8 9]]


Así se crean arrays a partir de listas:

In [8]:
lista = [1,2,3,4,5,6]
array = np.array(lista)

print(lista)
print(array)

[1, 2, 3, 4, 5, 6]
[1 2 3 4 5 6]


Así se crean listas a partir de arrays:

In [54]:
array = np.array([1, 2, 3, 4, 5, 6])
lista = list(array)

print(array)
print(lista)

[1 2 3 4 5 6]
[1, 2, 3, 4, 5, 6]


### Operaciones

Las operaciones entre arrays son las mismas que se pueden ejecutar entre vectores y matrices. Además hay otras que Numpy nos provee. Algunas son:

In [9]:
vec1 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
vec2 = np.array([2, 4 , 6, 8, 10, 12, 14, 16 ,18])
vec3 = np.array([1,0,0])
Mat1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
Mat2 = np.array([[2,4,6],[8,10,12],[14,16,18]])
Mat3 = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
vec4 = np.array([Mat1,Mat2])

print("Suma vectorial entre vec1 y vec2 (suma componente a componente)")
print(vec1 + vec2) # Suma vectorial entre vec1 y vec2 (suma componente a componente)
print("\n") # Se imprime un enter para dar algo de espacio

print("Suma matricial entre Mat1 y Mat2 (suma componente a componente)")
print(Mat1 + Mat2) # Suma matricial entre Mat1 y Mat2 (suma componente a componente)
print("\n")

print("Producto NO vectorial (no es el producto punto) entre vec1 y vec2. Este producto se llama producto de Hadamard y es un producto donde la multiplicación se hace componente a componente, retornando otro vector")
print(vec1*vec2) # Producto NO vectorial (no es el producto punto) entre vec1 y vec2. Este producto se llama producto de Hadamard y es un producto donde la multiplicación se hace componente a componente, retornando otro vector
print("\n")

print("Division NO vectorial entre vec1 y vec2. Esta división se llama división de Hadamard y es una division componente a componente, retornando otro vector")
print(vec1/vec2) # Division NO vectorial entre vec1 y vec2. Esta división se llama producto de Hadamard y es una division componente a componente, retornando otro vector
print("\n")

print("Se suma una constante a todas las componentes del array, sea vector o matriz")
print(Mat1 + 4.3) # Se suma una constante a todas las componentes del array, sea vector o matriz
print("\n")

print("Se multiplica una constante a todas las componentes del array, sea vector o matriz")
print(4.3*Mat1) # Se multiplica una constante a todas las componentes del array, sea vector o matriz
print("\n")

print("Producto de Hadamard entre Mat1 y Mat2")
print(Mat1*Mat2) # Producto de Hadamard entre Mat1 y Mat2
print("\n")

print("Seleccionar una parte de un vector, desde el elemento i=1 (segundo elemento) hasta el i=3 (cuarto elemento)")
print(vec1[1:3]) # Seleccionar una parte de un vector, desde el elemento i=1 (segundo elemento) hasta el i=3 (cuarto elemento)
print("\n")

print("Seleccionar una parte de un vector, desde el primer elemento hasta el i=4 (quinto elemento). Tambien se vale vec1[0:5]")
print(vec1[:5]) # Seleccionar una parte de un vector, desde el primer elemento hasta el i=4 (quinto elemento). Tambien se vale vec1[0:5]
print("\n")

print("Seleccionar una parte de un vector, desde el elemento i=4 (quinto elemento) hasta el último")
print(vec1[4:]) # Seleccionar una parte de un vector, desde el elemento i=4 (quinto elemento) hasta el último. 
print("\n")

print("Seleccionar una parte de una matriz Mat3, en las filas se escoge desde la i=1 (segunda fila) hasta la i=2 (tercera fila). En columnas se escoje desde la j=0 (primera columna) hasta la j=1 (segunda columna). Tambien se vale Mat3[1:3,:2]")
print(Mat3[1:3,0:2]) # Seleccionar una parte de una matriz Mat3, en las filas se escoge desde la i=1 (segunda fila) hasta la i=2 (tercera fila). En columnas se escoje desde la j=0 (primera columna) hasta la j=1 (segunda columna). Tambien se vale Mat3[1:3,:2]
print("\n")

print("Seleccionar una parte de una matriz Mat3, en las filas se escoge desde la i=2 (tercera fila) hasta la última. En columnas se escoje desde la j=0 (primera columna) hasta la última. Tambien se vale Mat3[2:,0:]")
print(Mat3[2:,:]) # Seleccionar una parte de una matriz Mat3, en las filas se escoge desde la i=2 (tercera fila) hasta la última. En columnas se escoje desde la j=0 (primera columna) hasta la última. Tambien se vale Mat3[2:,0:]
print("\n")

print("Seleccionar el primer vector columna de una matriz Mat1")
print(Mat1[:,0]) # Seleccionar el primer vector columna de una matriz Mat1
print("\n")

print("Seleccionar el segundo vector columna de una matriz Mat1")
print(Mat1[:,1]) # Seleccionar el segundo vector columna de una matriz Mat1
print("\n")

print("Seleccionar el primer vector fila de una matriz Mat1")
print(Mat1[0,:]) # Seleccionar el primer vector fila de una matriz Mat1
print("\n")

print("Seleccionar el segundo vector fila de una matriz Mat1")
print(Mat1[1,:]) # Seleccionar el segundo vector fila de una matriz Mat1
print("\n")

print("Producto vectorial (punto) entre los vectores vec1 y vec2")
print(np.dot(vec1,vec2)) # Producto vectorial (punto) entre los vectores vec1 y vec2
print("\n")

print("Producto entre la matriz Mat1 y el vector vec3")
print(np.dot(Mat1,vec3)) # Producto entre la matriz Mat1 y el vector vec3
print("\n")

print("Producto matricial entre las matrices Mat1 y Mat2")
print(np.matmul(Mat1,Mat2)) # Producto matricial entre las matrices Mat1 y Mat2
print("\n")

print("Retorna el tamaño de la matriz, el número de filas y el numero de columnas, respectivamente")
print(np.shape(Mat1), np.shape(Mat1)[0], np.shape(Mat1)[1]) # Retorna el tamaño de la matriz, el número de filas y el numero de columnas, respectivamente
print("\n")

print("Transpuesta de la matriz Mat1.")
print(np.transpose(Mat1)) # Transpuesta de la matriz Mat1.
print("\n")

print("Reflejar una matriz respecto al eje horizontal que cruza por la mitad de la matriz")
print(np.flip(Mat1,0)) # Reflejar una matriz respecto al eje horizontal que cruza por la mitad de la matriz
print("\n")

print("Reflejar una matriz respecto al eje vertical que cruza por la mitad de la matriz")
print(np.flip(Mat1,1)) # Reflejar una matriz respecto al eje vertical que cruza por la mitad de la matriz
print("\n")

print("Rotar 90 grados una matriz en sentido antihorario")
print(np.rot90(Mat1)) # Rotar 90 grados una matriz en sentido antihorario
print("\n")

print("Rotar 90 grados una matriz en sentido antihorario 3 veces")
print(np.rot90(Mat1,3)) # Rotar 90 grados una matriz en sentido antihorario
print("\n")

print("Todas las columnas se corren una posición a la derecha (la col 0 es ahora la 1, la 1 es ahora la 2, ..., y la última se vuelve la primera)")
print(np.roll(Mat1,+1,axis=1)) # Todas las columnas se corren una posición a la derecha (la col 0 es ahora la 1, la 1 es ahora la 2, ..., y la última se vuelve la primera)
print("\n")

print("Todas las columnas se corren dos posiciones a la derecha")
print(np.roll(Mat1,+2,axis=1)) # Todas las columnas se corren dos posiciones a la derecha
print("\n")

print("Todas las filas se corren una posición hacia abajo (la fila 0 es ahora la 1, la 1 es ahora la 2, ..., y la última se vuelve la primera)")
print(np.roll(Mat1,+1,axis=0)) # Todas las filas se corren una posición hacia abajo (la fila 0 es ahora la 1, la 1 es ahora la 2, ..., y la última se vuelve la primera)
print("\n")

print("Todas las filas se corren dos posiciones hacia abajo")
print(np.roll(Mat1,+2,axis=0)) # Todas las filas se corren dos posiciones hacia abajo
print("\n")

print("Convertir una matriz en vector. O sea, poner todos los elementos de una matriz pero ahora organziados en un vector")
print(np.ravel(Mat1)) # Convertir una matriz en vector. O sea, poner todos los elementos de una matriz pero ahora organziados en un vector
print("\n")

print("Sumar todos los elementos dentro de un vector")
print(np.sum(vec1)) # Sumar todos los elementos dentro de un vector
print("\n")

print("Promediar todos los elementos dentro de un vector")
print(np.mean(vec1)) # Promediar todos los elementos dentro de un vector
print("\n")

print("Sumar todos los elementos dentro de una matriz")
print(np.sum(Mat1)) # Sumar todos los elementos dentro de una matriz
print("\n")

print("Se obtiene un vector, cuyas componentes son las sumas de los elementos de cada vector fila")
print(np.sum(Mat1, axis=1)) # Se obtiene un vector, cuyas componentes son las sumas de los elementos de cada vector fila
print("\n")

print("Se obtiene un vector, cuyas componentes son las sumas de los elementos de cada vector columna")
print(np.sum(Mat1, axis=0)) # Se obtiene un vector, cuyas componentes son las sumas de los elementos de cada vector columna
print("\n")

print("Se obtiene un array (en este caso matriz), el cual es la suma de los arrays (en este caso matrices) contenidos en vec4")
print(np.sum(vec4, axis=0)) # Se obtiene un array, el cual es la suma de los arrays (en este caso matrices) contenidos en vec4
print("\n")

print("Se obtiene un vector, cuyas componentes son los promedios de los elementos de cada vector fila")
print(np.mean(Mat1, axis=1)) # Se obtiene un vector, cuyas componentes son los promedios de los elementos de cada vector fila
print("\n")

print("Se obtiene un vector, cuyas componentes son los promedios de los elementos de cada vector columna")
print(np.mean(Mat1, axis=0)) # Se obtiene un vector, cuyas componentes son los promedios de los elementos de cada vector columna
print("\n")

print("Se obtiene un array (en este caso matriz), el cual es el promedio de los arrays (en este caso matrices) contenidos en vec4")
print(np.mean(vec4, axis=0)) # Se obtiene un array (en este caso matriz), el cual es el promedio de los arrays (en este caso matrices) contenidos en vec4
print("\n")

print("Se obtiene el valor mínimo de un array (matriz o vector)")
print(np.amin(Mat1)) # Se obtiene el valor mínimo de un array (matriz o vector)
print("\n")

print("Se obtiene el valor máximo de un array (matriz o vector)")
print(np.amax(Mat1)) # Se obtiene el valor máximo de un array (matriz o vector)
print("\n")

print("Se convierte el vector vec1 en una matriz de tamaño 3x3")
print(vec1.reshape(3,3)) # Se convierte el vector vec1 en una matriz de tamaño 3x3
print("\n")

Suma vectorial entre vec1 y vec2 (suma componente a componente)
[ 3  6  9 12 15 18 21 24 27]


Suma matricial entre Mat1 y Mat2 (suma componente a componente)
[[ 3  6  9]
 [12 15 18]
 [21 24 27]]


Producto NO vectorial (no es el producto punto) entre vec1 y vec2. Este producto se llama producto de Hadamard y es un producto donde la multiplicación se hace componente a componente, retornando otro vector
[  2   8  18  32  50  72  98 128 162]


Division NO vectorial entre vec1 y vec2. Esta división se llama producto de Hadamard y es una division componente a componente, retornando otro vector
[0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5]


Se suma una constante a todas las componentes del array, sea vector o matriz
[[ 5.3  6.3  7.3]
 [ 8.3  9.3 10.3]
 [11.3 12.3 13.3]]


Se multiplica una constante a todas las componentes del array, sea vector o matriz
[[ 4.3  8.6 12.9]
 [17.2 21.5 25.8]
 [30.1 34.4 38.7]]


Producto de Hadamard entre Mat1 y Mat2
[[  2   8  18]
 [ 32  50  72]
 [ 98 128 162]]


Se

También hay algunas formas de crear arrays bajo ciertos parámetros dados, sin necesidad de crearlos desde listas. A continuación se muestran algunos ejemplos de esto

In [10]:
print("Crear array (vector) con 30 elementos, que varien desde 0 hasta 20: (20-0)/30")
print(np.linspace(0,20,30)) # Crear array con 30 elementos, que varien desde 0 hasta 20: (20-0)/30
print("\n")

print("Crear array (vector) de zeros con 20 elementos")
print(np.zeros(20)) # Crear array (vector) de zeros con 20 elementos
print("\n")

print("Crear array (matriz) de zeros con 10x10 elementos")
print(np.zeros((10,10))) # Crear array (matriz) de zeros con 10x10 elementos
print("\n")

print("Crear array (vector) de unos con 20 elementos")
print(np.ones(20)) # Crear array (vector) de unos con 20 elementos
print("\n")

print("Crear array (matriz) de unos con 10x10 elementos")
print(np.ones((10,10))) # Crear array (matriz) de unos con 10x10 elementos
print("\n")

print("Crear array (matriz) de numeros aleatorios entre 0 y 1 con 4x5 elementos")
print(np.random.rand(4,5)) # Crear array (matriz) de numeros aleatorios entre 0 y 1 con 4x5 elementos
print("\n")

print("Crear array vector de numeros enteros entre 0 y 9")
print(np.arange(10)) # Crear array vector de numeros enteros entre 0 y 9
print("\n")

Crear array (vector) con 30 elementos, que varien desde 0 hasta 20
[ 0.          0.68965517  1.37931034  2.06896552  2.75862069  3.44827586
  4.13793103  4.82758621  5.51724138  6.20689655  6.89655172  7.5862069
  8.27586207  8.96551724  9.65517241 10.34482759 11.03448276 11.72413793
 12.4137931  13.10344828 13.79310345 14.48275862 15.17241379 15.86206897
 16.55172414 17.24137931 17.93103448 18.62068966 19.31034483 20.        ]


Crear array (vector) de zeros con 20 elementos
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


Crear array (matriz) de zeros con 10x10 elementos
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


Crear array (vector) de unos con 20 elementos
[1. 1. 1. 1. 1. 1. 1. 1. 1

También los elementos dentro de un array pueden ser convertidos todos a enteros o floats.

In [11]:
arr1 = np.array([1,2,3,4,5,6,7])
arr2 = np.array([1.2, 2.3, 3.4, 4.5, 5.6, 6.7])

print("Convertir todos los elementos del arr1 en floats")
print(arr1.astype(float)) # Convertir todos los elementos del arr1 en floats
print("\n")

print("Convertir todos los elementos del arr2 en enteros")
print(arr2.astype(int)) # Convertir todos los elementos del arr2 en enteros
print("\n")

Convertir todos los elementos del arr1 en floats
[1. 2. 3. 4. 5. 6. 7.]


Convertir todos los elementos del arr2 en enteros
[1 2 3 4 5 6]




### 1.5 Booleanos

Los booleanos solo pueden tener dos posibles valores, que son True o False. Estos booleanos pueden ser bastante útiles al momento de manejar condicionales o ciclos. Los booleanos se pueden obtener a través de expresiones matemáticas útiles que comparen dos elementos. Algunos ejemplos se pueden mostrar a continuación:

In [12]:
a,b,c,d = 1, 2, 3.4, 4.5
vec1 = np.array([1,2,3,4,5])
vec2 = np.array([6,7,8,9,10])

print("Se pregunta si a es mayor que b. Claramente la respuesta tiene que ser No (False)")
print(a>b) # Se pregunta si a es mayor que b. Claramente la respuesta tiene que ser No (False)
print("\n")

print("Se pregunta si a es igual que b. Claramente la respuesta tiene que ser No (False)")
print(a==b) # Se pregunta si a es igual que b. Claramente la respuesta tiene que ser No (False)
print("\n")

print("Se pregunta si a es distinto que b. Claramente la respuesta tiene que ser Si (True)")
print(a!=b) # Se pregunta si a es distinto que b. Claramente la respuesta tiene que ser Si (True)
print("\n")

print("Se pregunta si el array vec1 es igual al array vec2. Claramente la respuesta tiene que ser No (False)")
print((vec1==vec2).all()) # Se pregunta si el array vec1 es igual al array vec2. Claramente la respuesta tiene que ser No (False)
print("\n")

Se pregunta si a es mayor que b. Claramente la respuesta tiene que ser No (False)
False


Se pregunta si a es igual que b. Claramente la respuesta tiene que ser No (False)
False


Se pregunta si a es distinto que b. Claramente la respuesta tiene que ser Si (True)
True


Se pregunta si el array vec1 es igual al array vec2. Claramente la respuesta tiene que ser No (False)
False




### Operaciones

Las operaciones entre booleanos son las mismas operaciones entre numeros binarios. Las básicas son and y or, aunque existen más como xor, nand, nor, etc. A continuación se meustran algunos ejemplos.

In [13]:
a,b = True, False

print("Retorna el valor de True(1) AND True(1)")
print(a and a) # Retorna el valor de True(1) AND True(1)
print("\n")

print("Retorna el valor de True(1) AND False(0)")
print(a and b) # Retorna el valor de True(1) AND False(0)
print("\n")

print("Retorna el valor de True(1) AND True(1)")
print(a & a) # Retorna el valor de True(1) AND True(1). Notar que "and" se puede cambiar por &
print("\n")

print("Retorna el valor de True(1) OR True(1)")
print(a or a) # Retorna el valor de True(1) OR True(1)
print("\n")

print("Retorna el valor de True(1) OR False(0)")
print(a or b) # Retorna el valor de True(1) OR False(0)
print("\n")

print("Retorna el valor de True(1) OR True(1)")
print(a | a) # Retorna el valor de True(1) OR True(1). Notar que "or" se puede cambiar por |
print("\n")

Retorna el valor de True(1) AND True(1)
True


Retorna el valor de True(1) AND False(0)
False


Retorna el valor de True(1) AND True(1)
True


Retorna el valor de True(1) OR True(1)
True


Retorna el valor de True(1) OR False(0)
True


Retorna el valor de True(1) OR True(1)
True




### 2. Funciones matemáticas en Python con Numpy

La librería Numpy permite, además de realizar operaciones con arrays, implementar funciones y constantes matemáticas importantes. A continuación se muestra un compendio de las posibles funciones matemáticas que pueden ser implementadas con Numpy.

In [14]:
import numpy as np 

x = 10.23

print("pi, se obtiene el valor de pi")
print(np.pi)
print("\n")

print("e, se obtiene el valor de la constante de euler")
print(np.e)
print("\n")

print("Sin(x), x tiene que estar en radianes")
print(np.sin(x))
print("\n")

print("Cos(x), x tiene que estar en radianes")
print(np.cos(x))
print("\n")

print("Tan(x), x tiene que estar en radianes")
print(np.tan(x))
print("\n")

print("Convertir x de grados a radianes")
print(np.radians(x))
print("\n")

print("Convertir x de radianes a grados")
print(np.degrees(x))
print("\n")

print("Sinh(x)")
print(np.sinh(x))
print("\n")

print("Cosh(x)")
print(np.cosh(x))
print("\n")

print("Tanh(x)")
print(np.tanh(x))
print("\n")

print("floor(x), función piso, que manda un decimal al entero más cercano por debajo")
print(np.floor(x))
print("\n")

print("ceil(x), función techo, que manda un decimal al entero más cercano por arriba")
print(np.ceil(x))
print("\n")

print("exp(x), función exponencial")
print(np.exp(x))
print("\n")

print("ln(x), función log natural")
print(np.log(x))
print("\n")

print("log_10(x), función log en base 10")
print(np.log10(x))
print("\n")

pi, se obtiene el valor de pi
3.141592653589793


e, se obtiene el valor de la constante de euler
2.718281828459045


Sin(x), x tiene que estar en radianes
-0.7209845231142057


Cos(x), x tiene que estar en radianes
-0.692951165256096


Tan(x), x tiene que estar en radianes
1.0404550266507586


Convertir x de grados a radianes
0.17854718247901993


Convertir x de radianes a grados
586.1358244188322


Sinh(x)
13861.255015991639


Cosh(x)
13861.25505206341


Tanh(x)
0.9999999973976549


floor(x), función piso, que manda un decimal al entero más cercano por debajo
10.0


ceil(x), función techo, que manda un decimal al entero más cercano por arriba
11.0


exp(x), función exponencial
27722.51006805505


ln(x), función log natural
2.325324579963535


log_10(x), función log en base 10
1.0098756337121602




Estas son solo algunas de las posibles funciones matemáticas de Numpy. Se pueden encontrar todas en https://numpy.org/doc/stable/reference/routines.math.html. Las funciones no solo se pueden aplicar a un número en específico, sino que pueden ser aplicadas a arrays completos (vectores,matrices,etc). Si se aplica una función matemática sobre un array, esta función se va a aplicar a cada una de las componentes, como se muestra a continuación:

In [15]:
theta = np.linspace(0,2*np.pi,50) # Se crea un vector (array) de 50 componentes, que tiene valores desde 0 hasta 2*pi

print("theta")
print(theta)
print("\n")

print("Sin(theta), theta tiene que estar en radianes")
print(np.sin(theta))
print("\n")

print("Cos(theta), theta tiene que estar en radianes")
print(np.cos(theta))
print("\n")


theta
[0.         0.12822827 0.25645654 0.38468481 0.51291309 0.64114136
 0.76936963 0.8975979  1.02582617 1.15405444 1.28228272 1.41051099
 1.53873926 1.66696753 1.7951958  1.92342407 2.05165235 2.17988062
 2.30810889 2.43633716 2.56456543 2.6927937  2.82102197 2.94925025
 3.07747852 3.20570679 3.33393506 3.46216333 3.5903916  3.71861988
 3.84684815 3.97507642 4.10330469 4.23153296 4.35976123 4.48798951
 4.61621778 4.74444605 4.87267432 5.00090259 5.12913086 5.25735913
 5.38558741 5.51381568 5.64204395 5.77027222 5.89850049 6.02672876
 6.15495704 6.28318531]


Sin(theta), theta tiene que estar en radianes
[ 0.00000000e+00  1.27877162e-01  2.53654584e-01  3.75267005e-01
  4.90717552e-01  5.98110530e-01  6.95682551e-01  7.81831482e-01
  8.55142763e-01  9.14412623e-01  9.58667853e-01  9.87181783e-01
  9.99486216e-01  9.95379113e-01  9.74927912e-01  9.38468422e-01
  8.86599306e-01  8.20172255e-01  7.40277997e-01  6.48228395e-01
  5.45534901e-01  4.33883739e-01  3.15108218e-01  1.91158629e

### 3. if/for/while/break/continue

En esta sección se discutirán los condicionales if, los ciclos for y while junto con los comandos break y continue para los ciclos. 

### 3.1 Condicionales (if)

Los condicionales sirven para, como dice su nombre, evaluar si una condición dada se cumple o no. Supongamos que queremos comparar tres números "a", "b" y "c". Si "a" es mayor a "b" y "a" es mayor que "c", imprimimos la frase: "El mayor es:" y a continuación el número "a". Si "b" es mayor que "a" y "b" es mayor que "c" entonces imprimimos la frase: "El mayor es:" y a continuación el número "b". Si "c" es mayor a "a" y "c" es mayor que "b", imprimimos la frase: "El mayor es:" y a continuación el número "c". En cualquier otro caso (por ejemplo, que a=b, a=c,  b=c, etc), imprimimos la frase "No se cumple". Veamos cómo se implementa.

In [55]:
a, b, c = 1, 2, 3

if((a>b) and (a>c)): # Primera condición
    print("El mayor es: " + str(a))
elif((b>a) and (b>c)): # Segunda condición
    print("El mayor es: " + str(b))
elif((c>a) and (c>b)): # Tercera condición
    print("El mayor es: " + str(c))
else: # Cuarta condición, la cual es que no se cumplan las tres anteriores
    print("No se cumple")

El mayor es: 3


Como se observa, dado que habíamos establecido tres condiciones, hay un if para la primera condición y dos elif para las siguientes dos condiciones. Si solo se tiene una condición entonces solo se pone el if y el else. Incluso es posible escribir el if solo, sin el else. 

Otro ejemplo muy sencillo es el de encontrar un número par. Un número par es aquel cuyo módulo 2 es igual a cero. Es decir, si "a" es par, entonces "a" % 2 = 0. Esta condición se puede implementar con un if y un else. 

In [17]:
a = 3

if (a % 2 == 0): # Si a mod 2 es cero...
    print("Es par") 
else: # De otra forma...
    print("No es par")

No es par


### 3.2 Bucle for

Un for sirve usualmente para realizar un mismo prodecimiento varias veces. También sirve para usar, por ejemplo, todos los elementos de un array para cierto objetivo. A continuación se muestran varios ejemplos del uso del ciclo for. 

Si por ejemplo quiero imprimir todos los valores de un array uno por uno puedo hacer lo siguiente:

In [18]:
arr1 = np.array([1, 2, "gato", "perro", 5])

for i in range(len(arr1)): # La variable "i" tomará los valores desde 0 hasta la longitud de arr1 menos uno, o sea desde 0 hasta 4, de tal forma que hay 5 índices (0,1,2,3,4) que representan cada uno de los elementos del array
    print(arr1[i]) # Imprimimos el i-esimo elemento de arr1

1
2
gato
perro
5


In [57]:
arr1 = np.array([1, 2, "gato", "perro", 5])

for i in range(0,5): # La variable "i" tomará los valores desde 0 hasta hasta 4, de tal forma que hay 5 índices (0,1,2,3,4) que representan cada uno de los elementos del array
    print(arr1[i]) # Imprimimos el i-esimo elemento de arr1

1
2
gato
perro
5


Se puede lograr lo mismo si en vez de recorrer indices "i" de 0 a 4, recorro directamente los elementos del array

In [19]:
arr1 = np.array([1, 2, "gato", "perro", 5])

for elem in arr1: # La variable "elem" será cada uno de los elementos del array arr1
    print(elem) # Imprimimos el elemento "elem"

1
2
gato
perro
5


También puedo obtener una mezcla de ambos métodos mostrados anteriormente, obteniendo directamente tanto el índice de un elemento del array como el elemento como tal:

In [58]:
arr1 = np.array([1, 2, "gato", "perro", 5])

for i,elem in enumerate(arr1): # "enumerate" sirve para obtener al mismo tiempo el índice y el elemento
    print(i, elem)

0 1
1 2
2 gato
3 perro
4 5


 No solo puedo recorrer vectores sino también matrices. En el caso de una matriz no puedo recorrer los elementos individuales directamente como en un vector, ya que pasa lo siguiente

In [21]:
Mat1 = np.array([[1,2,3],[4,5,6],[7,8,9]])

for i,elem in enumerate(Mat1): 
    print(i, elem) # Obtengo indices pero no los elementos individuales, sino los vectores fila de la matriz

0 [1 2 3]
1 [4 5 6]
2 [7 8 9]


Para recorrer los elementos individuales de la matriz correctamente se debe hacer algo como lo siguiente (Usualmente esta es la forma que yo uso):

In [22]:
for i in range(np.shape(Mat1)[0]): # Recordar que np.shape(Mat1)[0] es el numero de filas de la matriz
    for j in range(np.shape(Mat1)[1]): #Recordar que np.shape(Mat1)[1] es el numero de columnas de la matriz
        print(i,j,Mat1[i,j]) # Se imprime el indice i, el indice j y el correspondiente elemento (i,j) de la matriz

0 0 1
0 1 2
0 2 3
1 0 4
1 1 5
1 2 6
2 0 7
2 1 8
2 2 9


Lo anterior también se puede lograr de la siguiente forma:

In [23]:
for fila in Mat1: # Primero se recorren las filas
    for elemento in fila: # Luego se obtiene cada elemento de la fila llamada "fila"
        print(elemento) # Se imprime cada elemento de la matriz Mat1 en orden

1
2
3
4
5
6
7
8
9


y si se quiere hacer de la anterior manera pero obteniendo también los indices (i,j) de la matriz se puede hacer lo siguiente:

In [24]:
for i,fila in enumerate(Mat1):
    for j,elemento in enumerate(fila):
        print(i,j,elemento) # Se imprime el indice i, el indice j y el correspondiente elemento (i,j) de la matriz

0 0 1
0 1 2
0 2 3
1 0 4
1 1 5
1 2 6
2 0 7
2 1 8
2 2 9


Un ejemplo donde se puede usar el ciclo for es para sumar los elementos de un array. Este se mostrará a continuación:

In [60]:
Mat1 = np.array([[1,2],[3,4]])
Mat2 = np.array([[5,6],[7,8]])
Mat3 = np.array([[9,10],[11,12]])
arr1 = np.array([Mat1, Mat2, Mat3]) # Se crea un array que contiene las matrices Mat1, Mat2 y Mat3.

suma = np.zeros((np.shape(Mat1)[0],np.shape(Mat1)[1])) # Se crea una matriz de ceros del mismo tamaño de Mat1 (y de Mat2 y Mat3). Esta matriz servirá para albergar el valor de la suma de Mat1, Mat2 y Mat3

for matriz in arr1: # Se recorren directamente los elementos del arr1
    suma = suma + matriz # Suma comienza como una matriz de ceros, a la que en cada paso del for se le va sumando cada matriz dentro de arr1

print(arr1)
print("\n")
print(suma) 

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


[[15. 18.]
 [21. 24.]]


Sin embargo, Python proporciona con sus librerías caminos más cortos para realizar la suma anterior. De hecho, para sumar los elementos de arr1 (o en general, para sumar los arrays que se encuentran dentro de otro array) basta con hacer:

In [26]:
print(np.sum(arr1, axis=0)) # axis=0 sirve para especificar que se quieren sumar los elementos de arr1 (que es un array de arrays) horizontalmente, o sea Mat1 + Mat2 + Mat3, 

[[15 18]
 [21 24]]


Así como se pueden recorrer arrays, también se pueden recorrer listas:

In [27]:
lista = [1,2,3,4]

for elem in lista: # Obtenemos cada elemento "elem" de la lista
    print(elem) # Imprimimos cada elemento

1
2
3
4


Una forma creativa de usar las listas junto con los ciclos for es para crear arrays. Supongamos que deseamos crear un array (vector) que contenga los multiplos de 3 menores a 20 (0,3,6,9,12,15,18). Sin usar listas, solo con el ciclo for y arrays directamente podríamos hacerlo de la siguiente forma:

In [28]:
array_de_multiplos = np.zeros(7) # Creamos un array de ceros de 6 posiciones (ya que hay 6 multiplos de 3 menores a 20). Los ceros eventualmente serán reemplazados por los multiplos de 3.

ind2 = 0 # Creamos un índice auxiliar para ayudar a determinar el elemento del array_de_multiplos que queremos cambiar
for ind in range(20): # El indice "ind" va desde 0 hasta 19, que es justo el rango de numeros que necesitamos
    if(ind % 3 == 0): # Si ind modulo 3 = 0 (Si ind es multiplo de 3)
        array_de_multiplos[ind2] = ind
        ind2 = ind2 + 1 # Al final de cada ciclo, hacemos que el valor de ind2 aumente en una unidad, de forma que tome los valores 0,1,2,3,... y así podamos rellenar ordenadamente los elementos del array_de_multiplos. 

print(array_de_multiplos)
    


[ 0.  3.  6.  9. 12. 15. 18.]


Como se ve, efectivamente se logró obtener un array con los multiplos de 3 menores a 20, pero en realidad es un código muy rebuscado e inentendible que cuesta lograr hacer. En cambio, si nos ayudamos de la propiedad que tienen las listas de que pueden ser creadas como vacías y ser rellenadas poco a poco, podemos hacer el mismo código anterior de la siguiente manera:

In [29]:
lista_de_multiplos = [] # Creamos una lista vacia

for ind in range(20): # El indice "ind" va desde 0 hasta 19, que es justo el rango de numeros que necesitamos
    if(ind % 3 == 0): # Si ind modulo 3 = 0 (Si ind es multiplo de 3)...
        lista_de_multiplos.append(ind) # Si se cumple la condicion, agregamos el valor de ind a la lista

array_de_multiplos = np.array(lista_de_multiplos) # Convertimos la lista en array
print(array_de_multiplos)

[ 0  3  6  9 12 15 18]


Como se observó, no hubo necesidad ni de especificar el tamaño del array_de_multiplos ni de crear variables extra como "ind2" que parecían recursos complicados y mal implementados incluso. Usando listas se pueden facilitar muchas operaciones relacionadas con los arrays. 

Algo muy curioso es que también los for se pueden aplicar sobre strings, como se muestra a continuación:

In [30]:
string = "HolaMundo123" # Se define un string

for letra in string: # La variable "letra" tomará el valor de cada una de las letras o caracteres en el string
    print(letra) # Se imprime letra por letra en cada iteracion del for

H
o
l
a
M
u
n
d
o
1
2
3


### 3.3 break y continue

Dos utilidades interesantes que pueden ser aplicadas en bucles son los comandos break y continue. De forma muy superficial, break sirve para parar inmediatamente el bucle, mientras que continue sirve para saltarse algun paso del bucle. A continuación se muestra un ejemplo para cada uno

### break

El break, al igual que continue, van asociados a alguna condición que debe cumplirse. Por ejemplo. Supongamos que tenemos un array de 30 elementos, que son numeros del 1 al 20 y queremos imprimirlos todos. Sin embargo queremos que, una vez se encuentre un numero mayor a 11, el ciclo se pare y se dejen de imprimir los elementos del array. Esto se puede lograr de la siguiente manera

In [31]:
arr = np.linspace(1,20,30) # Array con 30 componentes, con números que van del 1 al 20
print(arr) # Se imprime el array
print("\n")

for elem in arr: # elem toma el valor de cada uno de los elementos de array llamado "arr"
    if(elem>11): # Si el elemento dentro del array es mayor a 11...
        break # ...Termine el ciclo for
    else: # Sino...
        print(elem) # ...lo imprime

[ 1.          1.65517241  2.31034483  2.96551724  3.62068966  4.27586207
  4.93103448  5.5862069   6.24137931  6.89655172  7.55172414  8.20689655
  8.86206897  9.51724138 10.17241379 10.82758621 11.48275862 12.13793103
 12.79310345 13.44827586 14.10344828 14.75862069 15.4137931  16.06896552
 16.72413793 17.37931034 18.03448276 18.68965517 19.34482759 20.        ]


1.0
1.6551724137931034
2.310344827586207
2.9655172413793105
3.6206896551724137
4.275862068965517
4.931034482758621
5.586206896551724
6.241379310344827
6.896551724137931
7.551724137931034
8.206896551724139
8.862068965517242
9.517241379310345
10.172413793103448
10.827586206896552


Como se observa, efectivamente solo los números menores a 11 que se encontraban dentro del array fueron impresos. Una vez que Python encontró un numero mayor o igual a 11, se detuvo el ciclo for y se dejaron de imprimir los componentes del array.

### continue

En el caso de continue, este sirve cuando se quieran pasar por alto ciertas cosas dada una condición. Por ejemplo, supongamos que tenemos un array de 30 elementos, que son numeros del 1 al 20 y queremos imprimirlos todos. Sin embargo queremos que se pasen por alto los numeros entre 10 y 15 al momento de imprimir cada elemento del array. Esto se puede lograr de la siguiente manera:

In [32]:
arr = np.linspace(1,20,30) # Array con 30 componentes, con números que van del 1 al 20
print(arr) # Se imprime el array
print("\n")

for elem in arr: # elem toma el valor de cada uno de los elementos de array llamado "arr"
    if(elem>=10 and elem <=15): # Si el elemento dentro del array es mayor o igual a 10 y menor o igual a 15...
        continue # ...paselo por alto
    else: # Sino...
        print(elem) # ...lo imprime

[ 1.          1.65517241  2.31034483  2.96551724  3.62068966  4.27586207
  4.93103448  5.5862069   6.24137931  6.89655172  7.55172414  8.20689655
  8.86206897  9.51724138 10.17241379 10.82758621 11.48275862 12.13793103
 12.79310345 13.44827586 14.10344828 14.75862069 15.4137931  16.06896552
 16.72413793 17.37931034 18.03448276 18.68965517 19.34482759 20.        ]


1.0
1.6551724137931034
2.310344827586207
2.9655172413793105
3.6206896551724137
4.275862068965517
4.931034482758621
5.586206896551724
6.241379310344827
6.896551724137931
7.551724137931034
8.206896551724139
8.862068965517242
9.517241379310345
15.413793103448276
16.06896551724138
16.724137931034484
17.379310344827587
18.03448275862069
18.689655172413794
19.344827586206897
20.0


Como se observa, efectivamente solo los números menores a 15 y mayores a 10 que se encontraban dentro del array no fueron impresos. Una vez que Python encontró un numero mayor a 10 o menor a 15, el ciclo for los ignoró y paso de largo sin tenerlos en cuenta.

Personalmente no he usado casi nunca (o nunca) break y continue. Sin embargo es bueno saber que existen.

### 3.4 Bucle while

Otro tipo de bucle es el bucle while. Este bucle siempre se asocia con una condición, sobre la cual corre. Por ejemplo, supongamos que quiero rellenar una lista con numeros enteros desde el 0 hasta el 20. Esto se puede lograr con un while de la siguiente manera:

In [33]:
ind = 0 # Primero se crea un indice
lista = [] # Creamos una lista vacía que vamos a ir rellenando

while (ind<=20): # Mientras el indice sea menor o igual a 20...
    lista.append(ind) # Agregamos el indice "ind" a la lista
    ind = ind + 1 # En cada iteración del while se le va sumando una unidad al indice "ind" para que este vaya cambiando de valor. Esto no se hace automáticamente como en el for. 

print(lista)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]


Generalmente lo más usado es el ciclo for. Sin embargo también es bueno saber que existen otros bucles o ciclos, como while.

### 4. Funciones 

Una función sirve para agrupar distintas acciones que se pueden hacer sobre ciertas variables. Siguen las mismas reglas que una función matemática: tienen ciertas variables de entrada que pueden producir otras variables de salida. Un ejemplo de una función sencilla puede ser el siguiente:

In [34]:
def suma(a,b): # Definimos una función llamada suma, cuyos parámetros de entrada son a y b
    resultado = a+b
    return resultado # La salida será el resultado de la suma de a y b

x = 5.2 # Definimos dos numeros
y = 10.1

print(suma(x,y)) # Imprimimos la suma de x con y

15.3


Las entradas y salidas de una función no solo se limitan a ser netamente números, sino que pueden ser cualquier tipo de variable:

In [35]:
vec1 = np.array([1,2,3,4])
vec2 = np.array([5,6,7,8])
Mat1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
Mat2 = np.array([[2,4,6],[8,10,12],[14,16,18]])
list1 = [1,2,3,4]
list2 = [5,6,7,8]
str1 = "Hola"
str2 = "Mundo"

print("Funcion suma aplicada a dos vectores")
print(suma(vec1,vec2))
print("\n")

print("Funcion suma aplicada a dos matrices")
print(suma(Mat1,Mat2))
print("\n")

print("Funcion suma aplicada a dos listas")
print(suma(list1,list2))
print("\n")

print("Funcion suma aplicada a dos strings")
print(suma(str1,str2))
print("\n")

Funcion suma aplicada a dos vectores
[ 6  8 10 12]


Funcion suma aplicada a dos matrices
[[ 3  6  9]
 [12 15 18]
 [21 24 27]]


Funcion suma aplicada a dos listas
[1, 2, 3, 4, 5, 6, 7, 8]


Funcion suma aplicada a dos strings
HolaMundo




Otro ejemplo de algo que podemos convertir en una función es el ejemplo que se dió para explicar el condicional (if). El ejemplo pretendía encontrar el mayor de tres números y era el siguiente:

In [36]:
a,b,c = 1,2,3

if((a>b) and (a>c)): # Primera condición
    print("El mayor es: " + str(a))
elif((b>a) and (b>c)): # Segunda condición
    print("El mayor es: " + str(b))
elif((c>a) and (c>b)): # Tercera condición
    print("El mayor es: " + str(c))
else: # Cuarta condición, la cual es que no se cumplan las tres anteriores
    print("No se cumple")

El mayor es:3


Podemos introducir estos condicionales en una función para que no solo funcionen para valores de "a","b" y "c" previamente definidos sino para cualesquiera valores. Esto se hace de la siguiente manera:

In [37]:
def mayor(a,b,c): # Definimos una función llamada "mayor" que tiene como parámetros de entrada tres numeros a,b y c
    if((a>b) and (a>c)): # Primera condición
        return "El mayor es: " + str(a), a # Se retorna un mensaje (string), como también el numero a 
    elif((b>a) and (b>c)): # Segunda condición
        return "El mayor es: " + str(b), b # Se retorna un mensaje (string), como también el numero b
    elif((c>a) and (c>b)): # Tercera condición
        return "El mayor es: " + str(c), c # Se retorna un mensaje (string), como también el numero c
    else: # Cuarta condición, la cual es que no se cumplan las tres anteriores
        return "No se cumple", 0 # Se retorna un mensaje (string), como también un número, que es cero. 

mensaje, numero = mayor(3,7,1) # Dado que la función tiene dos salidas, nosotros podemos obtener ambas salidas como se muestra acá. La primera salida de la fucnión se guarda en la variable "mensaje" y la segunda se guarda en la variable "numero"

print(mensaje)
print(numero)

El mayor es:7
7


En el caso anterior, los parámetros de entrada de la función son tres numeros a,b y c. Por otra parte, las salidas de la función son dos: la primera es un string y la segunda alguno de los tres números (o cero). Cada una de estas salidas se pueden obtener de forma separada como se muestra en los comentarios del código. 

Otro ejemplo sencillo que se puede realizar con una función es el siguiente. Supongamos que queremos tener una función que haga que los números pares dentro de una matriz se conviertan en cero. Esto se puede lograr de la siguiente manera:

In [38]:
def pares_a_cero(Mat1): # Definimos una funcion que tiene como parametro de entrada la matriz
    matriz = np.copy(Mat1) # Creamos una copia de la matriz de entrada, para que la matriz original no sea afectada. Si quiero que la matriz original cambie simplemente omito este paso
    for i in range(np.shape(matriz)[0]): # Recorremos las filas de la matriz
        for j in range(np.shape(matriz)[1]): # Recorremos las columnas de la matriz
            if (matriz[i,j] % 2 == 0): # Si la componente (i,j) de la matriz es un numero par...
                matriz[i,j] = 0 # ...convertimos esa componente (i,j) de la matriz en cero

    return matriz

Mat1 = np.array([[1,2,3],[4,5,6],[7,8,9]]) # Creamos una matriz 
Mat1_nueva = pares_a_cero(Mat1) # Aplicamos la función a la matriz y la matriz resultante la llamo Mat1_nueva

print("Imprimimos matriz original")
print(Mat1)
print("\n")

print("Imprimimos matriz modificada")
print(Mat1_nueva)
print("\n")

Imprimimos matriz original
[[1 2 3]
 [4 5 6]
 [7 8 9]]


Imprimimos matriz modificada
[[1 0 3]
 [0 5 0]
 [7 0 9]]




Si quiero que la matriz original sea modificada basta con hacer lo siguiente:

In [39]:
def pares_a_cero(matriz): # Definimos una funcion que tiene como parametro de entrada la matriz
    for i in range(np.shape(matriz)[0]): # Recorremos las filas de la matriz
        for j in range(np.shape(matriz)[1]): # Recorremos las columnas de la matriz
            if (matriz[i,j] % 2 == 0): # Si la componente (i,j) de la matriz es un numero par...
                matriz[i,j] = 0 # ...convertimos esa componente (i,j) de la matriz en cero
    # Podemos no retornar nada, es válido. Lo único que haría esta función sería modificar la matriz y ya, sin obtener ninguna salida

Mat1 = np.array([[1,2,3],[4,5,6],[7,8,9]]) # Creamos una matriz 

print("Imprimimos matriz original")
print(Mat1)
print("\n")

pares_a_cero(Mat1) # Aplicamos la función a la matriz. 

print("Imprimimos matriz modificada")
print(Mat1)
print("\n")

Imprimimos matriz original
[[1 2 3]
 [4 5 6]
 [7 8 9]]


Imprimimos matriz modificada
[[1 0 3]
 [0 5 0]
 [7 0 9]]




### 5. Recursividad

Se entiende por recursividad como la acción de usar una función dentro de ella misma. Se usa generalmente cuando se quieren resolver ecuaciones en variables discretas. El ejemplo más representativo en el que se usa recursividad es en la secuencia de Fibonacci. Esta dice que el n-ésimo termino de la secuencia, que podemos representar como f(n), está definido como:

f(n) = f(n-1) + f(n-2)

donde f(0) = 0 y f(1) = 1. Un ejemplo de la implementación de funciones y recursividad para encontrar el n-esimo numero de Fibonacci se muestraa continuación:

In [40]:
def fibonacci(n): # Se define la función "fibonacci", cuyo parámetro de entrada es el indice n, ya que queremos encontrar el n-ésimo numero de Fibonacci
    if(n == 0): # Si n = 0...
        f_n = 0 # f(n) = 0 
    elif(n == 1): # Si n = 1...
        f_n = 1 # f(n) = 1
    else: # Para cualquier otro valor de n...
        f_n = fibonacci(n-1) + fibonacci(n-2) # usamos la formula. Notar que estamos usando la función dentro de su propia definición. Esto es recursividad
    
    return f_n # La salida de la función será el n-esimo numero de fibonacci

print(fibonacci(10)) # Imprimimos el valor del n-esimo numero de fibonacci, para un determinado valor de n.

55


La recursividad no solo sirve para solucionar la ecuación que determina los números de Fibonacci, sino cualquier ecuación discreta. Supongamos que queremos solucionar la ecuación 

f(n) = 5*f(n-1) + 6*f(n-2)

con las condiciones iniciales f(0) = 1, f(1) = 2. La implementación de la solución de esta ecuacion para encontrar f(n) es:

In [41]:
def solucionador_discreto(n): 
    if(n == 0): # Si n = 0...
        f_n = 2 # f(n) = 2 
    elif(n == 1): # Si n = 1...
        f_n = 1 # f(n) = 3
    else: # Para cualquier otro valor de n...
        f_n = 5*solucionador_discreto(n-1) + 6*solucionador_discreto(n-2) # usamos la formula. Notar que estamos usando la función dentro de su propia definición. Esto es recursividad
    
    return f_n # La salida de la función será f(n)

print(solucionador_discreto(2)) # Imprimimos el valor del n-esimo numero de fibonacci, para un determinado valor de n.

17


### 6. Cargar archivos de texto externos

Hay distintas formas de cargar un archivo de texto externo. La manera en que carguemos un archivo depende del formato que este tenga. En la carpeta que contiene este archivo hay dos archivos de texto. Uno con datos netamente numéricos distribuidos en forma de matriz 8x8 (llamado matriz.txt) y otro con tres columnas de datos en donde incluso hay algunos que faltan (llamado documento_generico.txt). Para el primer archivo basta con hacer lo siguiente:

In [42]:
matriz = np.genfromtxt("matriz.txt") # Cargamos la matriz de datos dentro del txt a través del comando np.genfromtxt(). Por dentro de este comando se pone el nombre del archivo txt
print(matriz) # Se imprime la matriz
print(type(matriz)) # Se imprime el tipo de dato asociado a la variable "matriz"

[[ 1.  2.  3.  4.  5.  6.  7.  8.]
 [ 8.  7.  6.  5.  4.  3.  2.  1.]
 [10.  9.  8.  7.  6. 11. 12. 13.]
 [98. 76. 45. 32. 98. 76. 34. 12.]
 [ 1. 23. 45. 21. 34. 56. 32. 12.]
 [32. 43. 54. 65. 76. 86. 98. 12.]
 [23. 45. 14. 62. 75. 35. 65. 13.]
 [12. 31. 56. 16. 43. 23. 78. 97.]]
<class 'numpy.ndarray'>


Como se observa, solo basta con np.genfromtxt("matriz.txt") para cargar los datos desde el txt. De hecho, de una vez Python a través de este comando guarda la matriz como un array, que ya está listo para ser modificado, graficado, etc. Ahora intentemos hacer lo mismo para el otro archivo de texto.

In [43]:
datos = np.genfromtxt("documento_generico.txt")
print(datos)

ValueError: Some errors were detected !
    Line #3 (got 2 columns instead of 3)
    Line #4 (got 2 columns instead of 3)
    Line #5 (got 1 columns instead of 3)
    Line #7 (got 1 columns instead of 3)

Como se observa, si intentamos cargar los datos de la forma en que lo hicimos anteriormente se presenta un error. Esto es porque "documento_generico.txt" no tiene la misma cantidad de datos por fila. Es decir, hay algunas filas con dos datos, otras con uno y otras con 3, de forma que por eso se produce el error. Sin embargo no necesariamente debemos rendirnos por esto, ya que hay otras formas de leer estos archivos. La más genérica y que más he usado es la siguiente:

In [44]:
datos = open("documento_generico.txt", "r") # Abrimos el archivo con open(). Como primer parámetro ponemos el nombre del archivo y el segundo indica lo que se quiere hacer con el archivo (en este caso "r" significa "read").
lineas = datos.readlines() # Guardamos cada una de las lineas del archivo en una lista llamada lineas, que se obtiene al hacer datos.readlines()
print(lineas)

['momento posicion energia\n', '1 2 3\n', '4 5 \n', '6 7\n', '8\n', '9 10 11\n', '23 \n', '21 10 23\n', '90 87 62']


Ahora, para separar cada dato de cada linea usamos el comando split() (que se explicó en las operaciones que se hacen sobre strings). Esto lo hacemos de la siguiente manera:

In [45]:
lineas_con_datos_separados = [] # Creamos una lista vacía que contendrá cada una de las líneas del archivo, pero no con todos los datos de una misma fila agrupados en un solo string sino separados.

for linea in lineas: # Recorremos cada linea del archivo
    linea_con_datos_separados = linea.split() # Separamos los datos que se encuentran en una misma linea (fila) separados por un espacio y los agrupamos en una lista
    lineas_con_datos_separados.append(linea_con_datos_separados) # Agregamos a la lista las lineas con los datos ya separados

print(lineas_con_datos_separados) 

[['momento', 'posicion', 'energia'], ['1', '2', '3'], ['4', '5'], ['6', '7'], ['8'], ['9', '10', '11'], ['23'], ['21', '10', '23'], ['90', '87', '62']]


Como se puede observar, ya los datos de cada linea se encuentran separados, agrupados en listas. Si queremos obtener la primera columna de datos basta con hacer:

In [46]:
primera_columna = []  # Creamos una lista vacía que contendrá los datos de la primera columna

for linea in lineas_con_datos_separados: # Recorremos la lista que contiene las lineas(filas) del archivo ya con lso datos separados y agrupados en listas
    primer_dato_de_la_linea = linea[0] # Obtenemos el primer dato de cada linea, que es el que pertenece a la primera columna de los datos
    primera_columna.append(primer_dato_de_la_linea) # Añadimos a la lista de la priemra columna el primer dato de cada linea

print(primera_columna)

['momento', '1', '4', '6', '8', '9', '23', '21', '90']


Ahora, si queremos solo tener la primera columna sin el primer dato pro ejemplo (que es un título) entonces haríamos lo siguiente:

In [47]:
primera_columna = primera_columna[1:] # Redefinimos la primera columna, como la primera columna desde el segundo dato (i=1) hasta el último
print(primera_columna)

['1', '4', '6', '8', '9', '23', '21', '90']


Si nos damos cuenta, los componentes de la primera columna son strings, aunque deberían ser números. En ese paso podemos hacer lo siguiente:

In [48]:
primera_columna = np.array(primera_columna) # Redefinimos la primera columna, como ella misma pero ahora convertida en un array
primera_columna = primera_columna.astype(float) # Redefinimos la primera columna, como ella misma pero con sus datos ya no como strings sino como floats, por ejemplo.
print(primera_columna)

[ 1.  4.  6.  8.  9. 23. 21. 90.]


Ya con la columna convertida en array (vector) y con valores numéricos claros, podemos usarla para hacer operaciones, modificarla, etc. 

Las anteriores son las dos formas más comunes de cargar archivos.

### 7. Guardar arrays

Hay una forma bastante sencilla de guardar un array en un archivo de texto. Esto se hace de la sigueinte manera:

In [49]:
Mat1 = np.array([[1,2,3],[4,5,6],[7,8,9]]) # Creamos una matriz
np.savetxt("archivo.txt", Mat1) # La guardamos. Primero ponemos el nombre que queremos darle al archivo, luego ponemos el array que queremos poner.

Si en vez de guardar una matriz queremos por ejemplo guardar filas de datos (vectores fila uno abajo del otro), hacemos lo siguiente:

In [50]:
vec1 = np.array([1,2,3,4,5,6,7,8,9])
vec2 = np.array([9,8,7,6,5,4,3,2,1])
vec3 = np.array([1,3,5,7,9,2,4,6,8])

np.savetxt("archivo_2.txt",(vec1,vec2,vec3))

Si en vez de guardar filas de datos queremos guardar los arrays como vectores columna (vectores columnas una al lado de la otra), hacemos lo siguiente:

In [51]:
vec1 = np.array([1,2,3,4,5,6,7,8,9])
vec2 = np.array([9,8,7,6,5,4,3,2,1])
vec3 = np.array([1,3,5,7,9,2,4,6,8])

np.savetxt("archivo_3.txt",np.transpose((vec1,vec2,vec3)))